### PR TITLE
A new feature in octree refinement

### PR DESCRIPTION
**Pull request by mike-matveev**
It is not possible to start on octree refinement from a voxel mesh of arbitrary size. It gives flexibility in terms of size of elements, their aspect ratio and total number of elements.

### CODE REVIEW

**Comment by louisepb** [comment]
Hi Mikhail,
Is there a reason why you create new m_XVoxels etc rather than using the ones in the base class?
Thanks,
Louise

**Comment by mike-matveev** [comment]
Hi Louise,
My bad. It can be the ones from the base class indeed.
Thanks,
Mikhail

**Comment by louisepb** [comment]
Hi Mikhail,
The test fails again now. What number of voxels should be passed as parameters to get the same result as before?  I tried 1,1,1 but this now fails - again with small differences to nodal positions in about the 5th decimal place.  Is this what you'd expect?
Thanks,
Louise

**Comment by mike-matveev** [comment]
Hi Louise,

Yes, it is expected. I noticed that nodal coordinates are written with slightly lower precision then needed in an ideal case. So I increased the output precision.

Thanks,
Mikhail

**Comment by louisepb** [comment]
HI Mikhail,
That's fine then - I hadn't looked at the code that closely.  I'll update the test file.
Thanks,
Louise

**Pull request merged**
